groups:
  - name: deployment_alerts
    interval: 30s
    rules:
      # Deployment failure alerts
      - alert: DeploymentFailed
        expr: |
          kube_deployment_status_replicas_unavailable{
            namespace=~"running-app-.*",
            deployment=~"running-app-backend-.*"
          } > 0
        for: 5m
        labels:
          severity: critical
          team: platform
          component: deployment
        annotations:
          summary: 'Deployment {{ $labels.deployment }} has unavailable replicas'
          description: 'Deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} has {{ $value }} unavailable replicas for more than 5 minutes.'
          runbook_url: 'https://wiki.example.com/runbooks/deployment-unavailable'

      - alert: DeploymentReplicasMismatch
        expr: |
          kube_deployment_spec_replicas{
            namespace=~"running-app-.*",
            deployment=~"running-app-backend-.*"
          } != 
          kube_deployment_status_replicas_available{
            namespace=~"running-app-.*",
            deployment=~"running-app-backend-.*"
          }
        for: 10m
        labels:
          severity: warning
          team: platform
          component: deployment
        annotations:
          summary: 'Deployment {{ $labels.deployment }} replica mismatch'
          description: 'Deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} has replica mismatch for more than 10 minutes. Desired: {{ $labels.spec_replicas }}, Available: {{ $value }}'

      # Pod restart alerts
      - alert: HighPodRestartRate
        expr: |
          rate(kube_pod_container_status_restarts_total{
            namespace=~"running-app-.*",
            pod=~"running-app-backend-.*"
          }[15m]) > 0.1
        for: 5m
        labels:
          severity: warning
          team: platform
          component: stability
        annotations:
          summary: 'High restart rate for pod {{ $labels.pod }}'
          description: 'Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted {{ $value | humanize }} times per second over the last 15 minutes.'

      - alert: PodCrashLooping
        expr: |
          rate(kube_pod_container_status_restarts_total{
            namespace=~"running-app-.*",
            pod=~"running-app-backend-.*"
          }[15m]) > 0.5
        for: 1m
        labels:
          severity: critical
          team: platform
          component: stability
        annotations:
          summary: 'Pod {{ $labels.pod }} is crash looping'
          description: 'Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping with {{ $value | humanize }} restarts per second.'

      # Resource alerts
      - alert: HighMemoryUsage
        expr: |
          (
            container_memory_usage_bytes{
              namespace=~"running-app-.*",
              pod=~"running-app-backend-.*"
            } / 
            container_spec_memory_limit_bytes{
              namespace=~"running-app-.*",
              pod=~"running-app-backend-.*"
            }
          ) > 0.9
        for: 5m
        labels:
          severity: warning
          team: platform
          component: resources
        annotations:
          summary: 'High memory usage for pod {{ $labels.pod }}'
          description: 'Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its memory limit.'

      - alert: HighCPUUsage
        expr: |
          (
            rate(container_cpu_usage_seconds_total{
              namespace=~"running-app-.*",
              pod=~"running-app-backend-.*"
            }[5m]) / 
            container_spec_cpu_quota{
              namespace=~"running-app-.*",
              pod=~"running-app-backend-.*"
            }
          ) > 0.9
        for: 5m
        labels:
          severity: warning
          team: platform
          component: resources
        annotations:
          summary: 'High CPU usage for pod {{ $labels.pod }}'
          description: 'Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its CPU limit.'

      # HPA alerts
      - alert: HPAMaxedOut
        expr: |
          kube_horizontalpodautoscaler_status_current_replicas{
            namespace=~"running-app-.*",
            horizontalpodautoscaler=~"running-app-backend-.*"
          } >= 
          kube_horizontalpodautoscaler_spec_max_replicas{
            namespace=~"running-app-.*",
            horizontalpodautoscaler=~"running-app-backend-.*"
          }
        for: 10m
        labels:
          severity: warning
          team: platform
          component: scaling
        annotations:
          summary: 'HPA {{ $labels.horizontalpodautoscaler }} at maximum replicas'
          description: 'HPA {{ $labels.horizontalpodautoscaler }} in namespace {{ $labels.namespace }} has been at maximum replicas ({{ $value }}) for more than 10 minutes.'

      - alert: HPAScalingFailure
        expr: |
          kube_horizontalpodautoscaler_status_condition{
            namespace=~"running-app-.*",
            horizontalpodautoscaler=~"running-app-backend-.*",
            condition="ScalingLimited",
            status="true"
          } == 1
        for: 5m
        labels:
          severity: warning
          team: platform
          component: scaling
        annotations:
          summary: 'HPA {{ $labels.horizontalpodautoscaler }} scaling limited'
          description: 'HPA {{ $labels.horizontalpodautoscaler }} in namespace {{ $labels.namespace }} has limited scaling for more than 5 minutes.'

      # Deployment rollout alerts
      - alert: DeploymentRolloutStuck
        expr: |
          kube_deployment_status_condition{
            namespace=~"running-app-.*",
            deployment=~"running-app-backend-.*",
            condition="Progressing",
            status="false"
          } == 1
        for: 10m
        labels:
          severity: critical
          team: platform
          component: deployment
        annotations:
          summary: 'Deployment {{ $labels.deployment }} rollout stuck'
          description: 'Deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} rollout has been stuck for more than 10 minutes.'

      # Canary deployment alerts
      - alert: CanaryHighErrorRate
        expr: |
          (
            rate(http_requests_total{
              namespace=~"running-app-.*",
              deployment=~"running-app-backend-canary-.*",
              status=~"5.."
            }[5m]) / 
            rate(http_requests_total{
              namespace=~"running-app-.*",
              deployment=~"running-app-backend-canary-.*"
            }[5m])
          ) > 0.05
        for: 2m
        labels:
          severity: critical
          team: platform
          component: canary
        annotations:
          summary: 'High error rate in canary deployment'
          description: 'Canary deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} has {{ $value | humanizePercentage }} error rate.'

      - alert: CanaryHighLatency
        expr: |
          histogram_quantile(0.95,
            rate(http_request_duration_seconds_bucket{
              namespace=~"running-app-.*",
              deployment=~"running-app-backend-canary-.*"
            }[5m])
          ) > 1
        for: 5m
        labels:
          severity: warning
          team: platform
          component: canary
        annotations:
          summary: 'High latency in canary deployment'
          description: 'Canary deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} has 95th percentile latency of {{ $value | humanizeDuration }}.'

      # CI/CD pipeline alerts
      - alert: DeploymentPipelineFailed
        expr: |
          github_actions_workflow_run_conclusion{
            workflow_name="deploy-rolling.yml",
            conclusion="failure"
          } == 1
        for: 1m
        labels:
          severity: critical
          team: platform
          component: cicd
        annotations:
          summary: 'Deployment pipeline failed'
          description: 'GitHub Actions deployment workflow failed for repository {{ $labels.repository }}. Check the workflow run: {{ $labels.html_url }}'

      - alert: DeploymentPipelineSlow
        expr: |
          github_actions_workflow_run_duration_seconds{
            workflow_name="deploy-rolling.yml"
          } > 1800
        for: 1m
        labels:
          severity: warning
          team: platform
          component: cicd
        annotations:
          summary: 'Deployment pipeline running slow'
          description: 'GitHub Actions deployment workflow for repository {{ $labels.repository }} took {{ $value | humanizeDuration }} to complete.'

      # Service health alerts
      - alert: ServiceDown
        expr: |
          up{
            job="blackbox",
            instance=~".*running-app.*"
          } == 0
        for: 2m
        labels:
          severity: critical
          team: platform
          component: availability
        annotations:
          summary: 'Service {{ $labels.instance }} is down'
          description: 'Service {{ $labels.instance }} has been down for more than 2 minutes.'

      - alert: HighErrorRate
        expr: |
          (
            rate(http_requests_total{
              namespace=~"running-app-.*",
              status=~"5.."
            }[5m]) / 
            rate(http_requests_total{
              namespace=~"running-app-.*"
            }[5m])
          ) > 0.01
        for: 5m
        labels:
          severity: warning
          team: platform
          component: reliability
        annotations:
          summary: 'High error rate in {{ $labels.namespace }}'
          description: 'Error rate in namespace {{ $labels.namespace }} is {{ $value | humanizePercentage }} over the last 5 minutes.'
