version: 2
updates:
  # NPM dependencies - Regular updates
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 15
    target-branch: 'main'
    reviewers:
      - 'austinorphan'
    assignees:
      - 'austinorphan'
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps(dev)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    milestone: 4
    groups:
      # Security-critical dependencies (immediate updates)
      security-critical:
        applies-to: version-updates
        patterns:
          - 'express'
          - 'helmet'
          - 'cors'
          - 'bcrypt'
          - 'jsonwebtoken'
          - 'express-rate-limit'
          - 'winston'
        update-types:
          - 'minor'
          - 'patch'
          - 'security'

      # Production runtime dependencies
      production-deps:
        applies-to: version-updates
        patterns:
          - '@prisma/client'
          - 'prisma'
          - 'zod'
          - 'uuid'
          - 'date-fns'
          - 'dotenv'
        update-types:
          - 'minor'
          - 'patch'

      # React ecosystem (grouped for testing compatibility)
      react-ecosystem:
        applies-to: version-updates
        patterns:
          - 'react'
          - 'react-dom'
          - 'react-router-dom'
          - '@vitejs/plugin-react'
          - 'recharts'
        update-types:
          - 'minor'
          - 'patch'

      # Build tools and bundlers
      build-tools:
        applies-to: version-updates
        patterns:
          - 'vite'
          - '@vitejs/*'
          - 'typescript'
          - 'tsx'
          - 'autoprefixer'
          - 'postcss'
          - 'tailwindcss'
        update-types:
          - 'minor'
          - 'patch'

      # Testing framework dependencies
      testing-tools:
        applies-to: version-updates
        patterns:
          - 'vitest'
          - '@vitest/*'
          - 'jest'
          - '@jest/*'
          - 'playwright'
          - '@playwright/*'
          - '@testing-library/*'
          - 'jsdom'
          - 'supertest'
          - 'axe-core'
          - '@axe-core/*'
          - 'jest-axe'
        update-types:
          - 'minor'
          - 'patch'

      # Linting and formatting tools
      code-quality:
        applies-to: version-updates
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@typescript-eslint/*'
          - 'prettier'
          - '@commitlint/*'
          - 'husky'
        update-types:
          - 'minor'
          - 'patch'

      # Type definitions (low-risk updates)
      type-definitions:
        applies-to: version-updates
        patterns:
          - '@types/*'
        update-types:
          - 'minor'
          - 'patch'

      # Development utilities
      dev-utilities:
        applies-to: version-updates
        patterns:
          - 'concurrently'
          - 'cross-env'
          - 'nodemon'
          - 'complexity-report'
          - 'chromium-bidi'
          - 'pngjs'
        update-types:
          - 'minor'
          - 'patch'

    # Ignore packages that need careful manual review
    ignore:
      # Node.js major version updates require infrastructure changes
      - dependency-name: 'node'
        update-types: ['version-update:semver-major']

      # React major versions may have breaking changes
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']

      # Express major versions may have breaking middleware changes
      - dependency-name: 'express'
        update-types: ['version-update:semver-major']

      # Prisma major versions may require migration strategy changes
      - dependency-name: 'prisma'
        update-types: ['version-update:semver-major']
      - dependency-name: '@prisma/client'
        update-types: ['version-update:semver-major']

      # Testing framework major versions may change API significantly
      - dependency-name: 'jest'
        update-types: ['version-update:semver-major']
      - dependency-name: 'vitest'
        update-types: ['version-update:semver-major']
      - dependency-name: 'playwright'
        update-types: ['version-update:semver-major']

  # NPM dependencies - Security updates (daily)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    target-branch: 'main'
    reviewers:
      - 'austinorphan'
    assignees:
      - 'austinorphan'
    commit-message:
      prefix: 'security'
      include: 'scope'
    labels:
      - 'security'
      - 'dependencies'
      - 'automated'
      - 'priority-high'
    # Only security updates in this configuration
    update-types:
      - 'security'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '10:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    target-branch: 'main'
    reviewers:
      - 'austinorphan'
    assignees:
      - 'austinorphan'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'github-actions'
      - 'ci-cd'
      - 'automated'

    # Group related actions together
    groups:
      setup-actions:
        patterns:
          - 'actions/checkout'
          - 'actions/setup-node'
          - 'actions/cache'
          - 'actions/upload-artifact'
          - 'actions/download-artifact'

      github-script-actions:
        patterns:
          - 'actions/github-script'
          - 'github/super-linter'

      deployment-actions:
        patterns:
          - 'azure/*'
          - 'aws-actions/*'
          - 'google-github-actions/*'

  # Docker (if using containerization)
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '11:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 3
    target-branch: 'main'
    reviewers:
      - 'austinorphan'
    assignees:
      - 'austinorphan'
    commit-message:
      prefix: 'docker'
      include: 'scope'
    labels:
      - 'docker'
      - 'infrastructure'
      - 'automated'
