blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions & Support
    url: https://github.com/AustinOrphan/running-app-mvp/discussions
    about: Ask questions, get help, or discuss the Running Tracker MVP
  - name: 📚 Documentation
    url: https://github.com/AustinOrphan/running-app-mvp#readme
    about: Read the project documentation and setup instructions
  - name: 🔒 Critical Security Vulnerabilities
    url: mailto:security@runningapp.dev
    about: Report critical security vulnerabilities privately - will be forwarded to maintainers