name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Running Tracker MVP
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
        Please provide detailed information to help us understand and evaluate your request.

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: |
        As a [user type], I want [goal] so that [benefit].
        
        Currently, [describe the current limitation or problem]...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the feature you'd like to see implemented.
      placeholder: |
        I would like to see [describe your proposed solution]...
        
        This would work by [explain how it would function]...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I've also considered:
        - Alternative A: [description]
        - Alternative B: [description]
        
        Current workaround: [if any]...

  - type: dropdown
    id: area
    attributes:
      label: 🏗️ Area of Application
      description: Which part of the application would this feature affect?
      options:
        - Frontend (User Interface)
        - Backend (API/Server)
        - Database (Data Model)
        - Authentication
        - Mobile Experience
        - Performance
        - Developer Experience
        - Documentation
        - Multiple Areas
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority Level
      description: How important is this feature to you?
      options:
        - Critical - Blocks my primary use case
        - High - Significantly improves my workflow
        - Medium - Nice to have, would use regularly
        - Low - Would be convenient occasionally
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: 🏃‍♂️ User Type
      description: What type of runner/user would benefit from this feature?
      options:
        - Beginner runners
        - Recreational runners
        - Competitive runners
        - All users
        - Developers/Contributors
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 📋 Use Cases
      description: Provide specific examples of how this feature would be used.
      placeholder: |
        1. When [scenario], I would [action] to [outcome]
        2. During [situation], this feature would help by [benefit]
        3. [Another specific example]...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: What would make this feature complete? How would you test it?
      placeholder: |
        This feature would be complete when:
        - [ ] [Specific requirement 1]
        - [ ] [Specific requirement 2]
        - [ ] [Specific requirement 3]
        
        Testing scenarios:
        - [ ] [Test case 1]
        - [ ] [Test case 2]

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Mockups or Examples
      description: Any visual mockups, sketches, or examples from other apps?
      placeholder: |
        Attach mockups, screenshots, or links to similar features in other applications...
        
        Example apps that do this well: [app names]

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Additional Context
      description: Any other information that would be helpful?
      placeholder: |
        Additional considerations:
        - Performance implications: [any concerns]
        - Integration points: [what it connects to]
        - Future extensibility: [how it might grow]

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I would be interested in implementing this feature
        - label: I would be willing to help with testing
        - label: I would be willing to help with design/mockups
        - label: I would be willing to help with documentation

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem statement and use cases
          required: true
        - label: This feature aligns with the project's goals as a running tracker MVP
          required: true