name: 🔒 Security Issue
description: Report a security vulnerability (handled privately)
title: "[Security]: "
labels: ["security", "P0-critical"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT: Security Disclosure Policy** ⚠️
        
        If this is a **critical security vulnerability** that could be exploited, please:
        1. **DO NOT** create a public issue
        2. **DO NOT** include exploit details in this form
        3. **Contact the maintainers directly** via private channels first
        
        For **general security improvements** and **non-critical security issues**, you may proceed with this public issue.

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity Level
      description: How severe is this security issue?
      options:
        - Critical - Immediate exploitation possible (CONTACT PRIVATELY)
        - High - Could lead to significant security breach
        - Medium - Security improvement needed
        - Low - Minor security enhancement
        - General - Security best practices improvement
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: Describe the security concern (avoid exploit details for critical issues)
      placeholder: |
        General description of the security issue...
        
        ⚠️ For critical vulnerabilities, provide only high-level description here.
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: 🏗️ Affected Area
      description: Which part of the application is affected?
      options:
        - Authentication (JWT, passwords)
        - Authorization (access controls)
        - Input Validation
        - Data Exposure
        - API Security
        - Database Security
        - Frontend Security (XSS, etc.)
        - Infrastructure/Deployment
        - Dependencies
        - Multiple Areas
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: 📊 Potential Impact
      description: What could an attacker potentially achieve?
      placeholder: |
        Potential impact includes:
        - [Impact 1]
        - [Impact 2]
        
        Affected users: [who would be impacted]

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 General Steps (Non-Critical Issues Only)
      description: For non-critical issues, provide general reproduction steps
      placeholder: |
        ⚠️ Only provide detailed steps for non-critical security improvements.
        
        For critical vulnerabilities, contact maintainers privately first.
        
        General steps:
        1. [Step 1]
        2. [Step 2]
        3. [Observe security concern]

  - type: textarea
    id: mitigation
    attributes:
      label: 🛡️ Suggested Mitigation
      description: How do you suggest fixing this security issue?
      placeholder: |
        Suggested solutions:
        - [Solution 1]
        - [Solution 2]
        
        Security best practices to implement:
        - [Practice 1]
        - [Practice 2]

  - type: textarea
    id: references
    attributes:
      label: 📚 Security References
      description: Any relevant security standards, OWASP guidelines, or CVE references?
      placeholder: |
        Related security resources:
        - OWASP: [relevant guideline]
        - CVE: [if applicable]
        - Security standards: [if applicable]

  - type: input
    id: environment
    attributes:
      label: 🌐 Environment
      description: In what environment was this observed?
      placeholder: e.g., Development, Staging, Production, All environments

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Additional Context
      description: Any other security-related information?
      placeholder: |
        Additional security considerations:
        - Related security measures already in place
        - Dependencies or configurations involved
        - Compliance requirements

  - type: checkboxes
    id: disclosure
    attributes:
      label: 🤝 Responsible Disclosure
      description: Please confirm your understanding of responsible disclosure
      options:
        - label: I understand that critical security vulnerabilities should be reported privately first
          required: true
        - label: If this is critical, I will contact maintainers through private channels
          required: true
        - label: I will not publicly disclose exploit details for critical vulnerabilities
          required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have assessed the severity level appropriately
          required: true
        - label: I have not included exploit details for critical vulnerabilities
          required: true
        - label: I am following responsible disclosure practices
          required: true